### ISSUE TITLE
Attempting to run Apple2e Games

### ISSUE THREAD

**Issue by Godsbane** [flathub/org.mamedev.MAME#8]
I will preface this with i have no idea what i'm doing. I was asked to help someone else get an Apple2e game working. I have no issues with _normal_ MAME emulation.
`/var/lib/flatpak/exports/bin/org.mamedev.MAME -rompath /home/deck/Emulation/roms/apple2 apple2e -flop1 /home/deck/Emulation/roms/apple2/Zorro.dsk`

it will boot Apple ][ and then crash almost immediately after trying to load the disk with 

`/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = short int; _Alloc = std::allocator<short int>; reference = short int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

**Comment by rogs123** [comment]
Same error when trying to launch bbcmicro emulation:

_/var/lib/flatpak/exports/bin/org.mamedev.MAME -rompath /run/media/mmcblk0p1/Emulation/roms/bbcmicro/ bbcb -autoboot_delay "2" -flop1 /run/media/mmcblk0p1/Emulation/roms/bbcmicro/ChuckieEgg.ssd_

MAME will boot into the BBC emulator where I can enter commands. When I enter "*exec !boot", I get a few seconds of the rom running and then MAME exits out with:

_/usr/include/c++/12.1.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = short int; _Alloc = std::allocator<short int>; reference = short int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed._

Per above, normal MAME emulation for arcade roms works fine.

**Comment by jflatt** [comment]
It looks like it was the floppy disk drive sample sound playback.  I've put in a fix in the flatpak for now, will submit it upstream

**Comment by rogs123** [comment]
Works great! Test AppleII and BBCmicro. Thanks for fixing!
